# Generated by Django 2.0.2 on 2020-11-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('errors_kpi', models.CharField(max_length=60, null=True)),
                ('errors_work', models.CharField(max_length=60, null=True)),
                ('verified', models.CharField(max_length=60, null=True)),
                ('SIZE', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('file_name', models.CharField(max_length=50, null=True)),
                ('value', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('file_name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='verified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('file_name', models.CharField(max_length=50, null=True)),
                ('value', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
